### ISSUE TITLE
How do you redirect to a deep link?

### ISSUE THREAD

**Issue by fjvalles** [rikas/deeplink#2]
Given a deep link to an android app for example, how do you do a redirect_to in RoR?
If you put redirect_to "hello://some/path" RoR redirects to http://hello://some/path which is not useful.

**Comment by rikas** [comment]
Hi @fjvalles never used deeplinks in redirects using `redirect_to`, it makes sense that RoR will convert it to http (or https).

I guess that what you can do is redirect to a page where you can then open the deeplink using Javascript (I did this a couple of times).
